# -*- coding: utf-8 -*-
"""rk1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdpVl2qf6DZsN3sZiJhN4wMixW3OLl1N

# Рубежный контроль №1
## Тема: Методы обработки данных

**Студент:** Папин Алексей Владимирович

**Группа** ИУ5Ц-21М

### Задачи:
1. **Задача №1:** Построить график "Диаграмма рассеяния (scatter plot)" для пары произвольных колонок данных
2. **Задача №2:** Кодирование категориального признака методом Target (Mean) Encoding
3. **Задача №22:** Масштабирование числового признака по максимальному значению (MaxAbs Scaling)

**Набор данных:** Global E-Commerce Sales Dataset (Synthetic) | 2021–2024

## Импорт библиотек и загрузка данных
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MaxAbsScaler

PLOTS_DIR = 'plots'
os.makedirs(PLOTS_DIR, exist_ok=True)

df = pd.read_csv('ecommerce_sales_dataset.csv')
print(f"Размер набора данных: {df.shape}")
print("\nПервые 5 строк:")
df.head()

print("Информация о данных:")
df.info()
print("\nОписательная статистика:")
df.describe()

"""### Анализ описательной статистики

На основе полученных данных можно сделать следующие выводы:

1.  **Revenue (Выручка):**
    *   **Асимметрия:** Среднее значение (**528.44**) значительно превышает медиану (**164.60**), что указывает на правостороннее смещение распределения.
    *   **Выбросы:** Максимальное значение (**19 966.50**) аномально велико по сравнению с 75-м процентилем (**469.95**). Это свидетельствует о наличии экстремальных заказов.

2.  **Profit (Прибыль):**
    *   **Убытки:** Минимальное значение отрицательное (**-1572.90**), что говорит о наличии заказов с убытком.
    *   **Выбросы:** Максимальное значение (**9144.15**) многократно превышает 75-й процентиль (**118.48**), что также указывает на наличие выбросов.
    *   **Разброс:** Высокое стандартное отклонение (**420.49**) относительно медианы (**34.75**) подтверждает неоднородность данных.

**Вывод:** Наличие экстремальных значений в признаках `Revenue` и `Profit` требует проведения предобработки данных (удаления выбросов) для корректного построения графиков.

---
## Предобработка данных: удаление выбросов

Проанализируем признаки `Revenue` (выручка) и `Profit` (прибыль) на наличие выбросов с помощью метода межквартильного размаха (IQR).
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(data=df, y='Revenue', ax=axes[0], color='#2196F3')
axes[0].set_title('Boxplot: Revenue (до обработки)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Выручка (USD)')

sns.boxplot(data=df, y='Profit', ax=axes[1], color='#4CAF50')
axes[1].set_title('Boxplot: Profit (до обработки)', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Прибыль (USD)')

plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'outliers_before.png'), dpi=150, bbox_inches='tight')
plt.show()

def remove_outliers_iqr(dataframe, column):
    Q1 = dataframe[column].quantile(0.25)
    Q3 = dataframe[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = dataframe[(dataframe[column] < lower_bound) | (dataframe[column] > upper_bound)]
    cleaned = dataframe[(dataframe[column] >= lower_bound) & (dataframe[column] <= upper_bound)]
    print(f"{column}: выбросов = {len(outliers)} из {len(dataframe)} ({len(outliers)/len(dataframe)*100:.1f}%)")
    print(f"  Границы: [{lower_bound:.2f}, {upper_bound:.2f}]")
    return cleaned

print("Обнаружение выбросов (метод IQR):")
df_clean = remove_outliers_iqr(df, 'Revenue')
df_clean = remove_outliers_iqr(df_clean, 'Profit')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(data=df_clean, y='Revenue', ax=axes[0], color='#2196F3')
axes[0].set_title('Boxplot: Revenue (после обработки)', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Выручка (USD)')

sns.boxplot(data=df_clean, y='Profit', ax=axes[1], color='#4CAF50')
axes[1].set_title('Boxplot: Profit (после обработки)', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Прибыль (USD)')

plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'outliers_after.png'), dpi=150, bbox_inches='tight')
plt.show()

print(f"Размер данных до обработки: {df.shape}")
print(f"Размер данных после обработки: {df_clean.shape}")
print(f"Удалено строк: {len(df) - len(df_clean)}")
print(f"\nОписательная статистика после удаления выбросов:")
df_clean[['Revenue', 'Profit']].describe()

"""**Результат:** Выбросы удалены из признаков `Revenue` и `Profit` методом IQR. Дальнейший анализ проводится на очищенном наборе данных `df_clean`.

---
## Задача №1. Диаграмма рассеяния (Scatter Plot)

Построим scatter plot для пары признаков `Revenue` (выручка) и `Profit` (прибыль), чтобы проанализировать их корреляцию на очищенных данных.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import os

# Построение диаграммы рассеяния для пары колонок Revenue и Profit
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_clean, x='Revenue', y='Profit', alpha=0.5, color='#2196F3')

plt.title('Scatter Plot: Взаимосвязь выручки и прибыли (без выбросов)', fontsize=14, fontweight='bold')
plt.xlabel('Выручка (USD)', fontsize=12)
plt.ylabel('Прибыль (USD)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()

# Сохранение графика
plt.savefig(os.path.join(PLOTS_DIR, 'scatter_plot.png'), dpi=150, bbox_inches='tight')
plt.show()

"""### Анализ диаграммы рассеяния

На основе построенного графика можно сделать следующие выводы:

1.  **Линейная корреляция:** Наблюдается ярко выраженная положительная линейная зависимость между выручкой (`Revenue`) и прибылью (`Profit`). Это логично для торговых операций: чем выше объем продаж в денежном эквиваленте, тем выше итоговая прибыль.
2.  **Плотность данных:** Основная масса заказов сосредоточена в диапазоне выручки до 400 USD и прибыли до 100 USD.
3.  **Разброс (Дисперсия):** С увеличением выручки разброс значений прибыли также увеличивается (форма «воронки»), что может быть связано с различиями в маржинальности разных категорий товаров или вариативностью затрат на логистику.
4.  **Эффективность очистки:** Благодаря предварительному удалению выбросов методом IQR, масштаб графика позволяет детально рассмотреть структуру взаимосвязи, которая была бы скрыта при наличии экстремальных значений.

**Вывод по задаче №1:** Диаграмма рассеяния подтверждает гипотезу о прямой зависимости прибыли от выручки и демонстрирует отсутствие аномальных отклонений в очищенном наборе данных.

---
## Задача №2. Target (Mean) Encoding

Проведём кодирование категориального признака `Shipping_Method` (метод доставки) методом Target Encoding. Целевая переменная — `Shipping_Days` (дни доставки).
"""

print("Уникальные значения 'Shipping_Method':")
print(df_clean['Shipping_Method'].value_counts())
print(f"\nКоличество уникальных значений: {df_clean['Shipping_Method'].nunique()}")

target_means = df_clean.groupby('Shipping_Method')['Shipping_Days'].mean()
print("Среднее время доставки по методам (Target Encoding):")
print(target_means)

encoding_map = target_means.to_dict()
print("\nСловарь кодирования:")
print(encoding_map)

df_clean['Shipping_Method_Encoded'] = df_clean['Shipping_Method'].map(encoding_map)

print("\nРезультат кодирования (первые 10 строк):")
df_clean[['Shipping_Method', 'Shipping_Method_Encoded', 'Shipping_Days']].head(10)

plt.figure(figsize=(8, 5))
colors = ['#2196F3', '#4CAF50', '#FF9800', '#E91E63']
keys = np.array(list(encoding_map.keys()))
values = np.array(list(encoding_map.values()))
bars = plt.bar(keys, values, color=colors[:len(keys)], edgecolor='black', alpha=0.8)
plt.title('Target Encoding: Среднее время доставки по методам', fontsize=14, fontweight='bold')
plt.xlabel('Метод доставки', fontsize=12)
plt.ylabel('Среднее количество дней', fontsize=12)
plt.ylim(0, max(values) * 1.2)
for bar, val in zip(bars, values):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
             f'{val:.1f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'target_encoding.png'), dpi=150, bbox_inches='tight')
plt.show()

"""**Интерпретация:**
- Target Encoding заменяет категориальные значения на среднее значение целевой переменной
- Различия между методами доставки незначительны из-за синтетического характера данных

---
## Задача №22. Масштабирование по максимальному значению (MaxAbs Scaling)

Проведём масштабирование числового признака `Profit` (прибыль) методом MaxAbs Scaling.
"""

print("Статистика признака 'Profit' до масштабирования:")
print(df_clean['Profit'].describe())
print(f"\nМаксимальное значение: {df_clean['Profit'].max():.2f}")
print(f"Минимальное значение: {df_clean['Profit'].min():.2f}")

scaler = MaxAbsScaler()
df_clean['Profit_Scaled'] = scaler.fit_transform(df_clean[['Profit']])

print("Результат масштабирования (первые 10 строк):")
df_clean[['Profit', 'Profit_Scaled']].head(10)

print("\nСтатистика признака 'Profit' после масштабирования:")
print(df_clean['Profit_Scaled'].describe())
print(f"\nМаксимальное значение после масштабирования: {df_clean['Profit_Scaled'].max():.6f}")
print(f"Минимальное значение после масштабирования: {df_clean['Profit_Scaled'].min():.6f}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.histplot(data=df_clean, x='Profit', kde=False, ax=axes[0], color='#2196F3', bins=30, stat='density')
sns.kdeplot(data=df_clean, x='Profit', ax=axes[0], color='red')
axes[0].set_title('Распределение "Profit" до масштабирования', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Прибыль (USD)')
axes[0].set_ylabel('Частота')
axes[0].grid(axis='y', alpha=0.3)

sns.histplot(data=df_clean, x='Profit_Scaled', kde=False, ax=axes[1], color='green', bins=30, stat='density')
sns.kdeplot(data=df_clean, x='Profit_Scaled', ax=axes[1], color='red')
axes[1].set_title('Распределение "Profit" после MaxAbs Scaling', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Масштабированная прибыль')
axes[1].set_ylabel('Частота')
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'maxabs_scaling.png'), dpi=150, bbox_inches='tight')
plt.show()

"""**Интерпретация:**
- MaxAbs Scaling делит каждое значение на максимальное абсолютное значение признака
- Максимальное значение после масштабирования равно 1.0
- Отрицательные значения прибыли (убытки) сохраняют знак после масштабирования

---
## Заключение

В ходе выполнения рубежного контроля №1 были решены следующие задачи и сделаны выводы:

1. **Предобработка данных (Очистка от выбросов):**
   - Использование метода межквартильного размаха (IQR) позволило выявить и исключить около 20% аномальных значений в признаках `Revenue` и `Profit`. Это критически важный этап, так как экстремальные выбросы (максимальная выручка в 20 000 при медиане 164) искажали бы статистические показатели и визуализацию.

2. **Задача №1 (Диаграмма рассеяния):**
   - Построенный график продемонстрировал сильную положительную корреляцию между выручкой и прибылью. Характер распределения (форма «воронки») указывает на то, что с ростом объема сделки увеличивается и вариативность прибыли, что может свидетельствовать о разной маржинальности товаров. Очистка данных позволила визуализировать основную массу заказов в сопоставимом масштабе.

3. **Задача №2 (Target Encoding):**
   - Применение целевого кодирования к признаку `Shipping_Method` позволило перевести категориальные данные в числовой формат, сохранив информацию о взаимосвязи метода доставки со временем ожидания (`Shipping_Days`). Несмотря на то, что в синтетических данных средние значения по группам близки (11.2–11.5 дней), метод успешно продемонстрировал возможность подготовки признаков для моделей машинного обучения.

4. **Задача №22 (MaxAbs Scaling):**
   - Масштабирование признака `Profit` методом MaxAbs привело все значения к диапазону [-0.53, 1.0]. Данный метод был выбран как оптимальный для сохранения знака прибыли (убыток остается отрицательным) и разреженности данных, что важно для корректной работы линейных алгоритмов и нейронных сетей.

**Итог:** Все поставленные задачи выполнены в полном объеме, данные подготовлены и проанализированы в соответствии с требованиями для группы ИУ5Ц-21М.
"""